// src/pages/Login/ui/LoginPage.vue
<script setup lang="ts">
import { FormLayout } from '@/widgets/FormLayout';
import { LoginForm } from '@/widgets/Auth';
</script>

<template>
  <FormLayout
    title="Welcome back"
    subtitle="Please place your credentials in the appropriate fields."
  >
    <LoginForm />
  </FormLayout>
</template>

// src/components/pages/LoginPage/LoginPage.tsx
import { Login } from "@/components/interface";
import { AuthPageLayout } from "@/components/layout";

import { avatar } from "@/assets";

export const LoginPage = () => {
	return (
		<AuthPageLayout
			avatar={avatar}
			title="Log in to Grapegram"
			description="Please place your credentials in the appropriate fields."
		>
			<Login />
		</AuthPageLayout>
	);
};
